import { useEffect, useMemo, useState } from "react";
import {
  BarChart,
  Bar,
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from "recharts";

import DashboardLayout from "../components/DashboardLayout";
import { Card, StatCard, Badge, SectionLabel, EmptyState } from "../components/ui";
import { getTrendEngineAnalytics } from "../services/api";

const NAVY = "#16143f";
const OCHRE = "#a9762f";

export default function TrendEngine() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [selectedDomain, setSelectedDomain] = useState("");

  useEffect(() => {
    let mounted = true;

    async function load() {
      try {
        setLoading(true);
        setError("");

        const response = await getTrendEngineAnalytics();
        if (!mounted) return;

        setData(response.data);
      } catch (err) {
        if (mounted) setError(err.message || "Failed to load Trend Engine data.");
      } finally {
        if (mounted) setLoading(false);
      }
    }

    load();

    return () => {
      mounted = false;
    };
  }, []);

  const domainYearly = data?.domainYearly || [];
  const domainCAGR = data?.domainCAGR || [];
  const emergingDomains = data?.emergingDomains || [];
  const institutionCAGR = data?.institutionCAGR || [];
  const grantImpact = data?.grantImpact || [];
  const topResearchers = data?.topResearchers || [];

  // Unique domain list, derived from the yearly counts
  const domains = useMemo(() => {
    return [...new Set(domainYearly.map((row) => row.domain))].sort();
  }, [domainYearly]);

  // Default the selector to the first domain once data arrives
  useEffect(() => {
    if (!selectedDomain && domains.length > 0) {
      setSelectedDomain(domains[0]);
    }
  }, [domains, selectedDomain]);

  // Year-by-year series for the selected domain
  const domainSeries = useMemo(() => {
    return domainYearly
      .filter((row) => row.domain === selectedDomain)
      .sort((a, b) => a.year - b.year);
  }, [domainYearly, selectedDomain]);

  // Top 10 domains by CAGR
  const topCAGR = useMemo(() => {
    return [...domainCAGR].sort((a, b) => b.cagr - a.cagr).slice(0, 10);
  }, [domainCAGR]);

  const totals = useMemo(() => {
    return domainYearly.reduce(
      (acc, row) => ({
        publications: acc.publications + row.publications,
        patents: acc.patents + row.patents,
        grants: acc.grants + row.grants,
        theses: acc.theses + row.theses,
      }),
      { publications: 0, patents: 0, grants: 0, theses: 0 }
    );
  }, [domainYearly]);

  if (loading) {
    return (
      <DashboardLayout title="Trend Engine" description="Analytics generated by the Python Trend Engine">
        <p className="text-sm text-[var(--color-muted)]">Loading Trend Engine…</p>
      </DashboardLayout>
    );
  }

  if (error) {
    return (
      <DashboardLayout title="Trend Engine" description="Analytics generated by the Python Trend Engine">
        <EmptyState
          title="Could not load Trend Engine data"
          description={error}
        />
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout title="Trend Engine" description="Analytics generated by the Python Trend Engine">
      <div className="space-y-8">
        {/* Totals */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          <StatCard label="Publications" value={totals.publications.toLocaleString()} />
          <StatCard label="Patents" value={totals.patents.toLocaleString()} />
          <StatCard label="Grants" value={totals.grants.toLocaleString()} />
          <StatCard label="Theses" value={totals.theses.toLocaleString()} />
        </div>

        {/* Yearly output for one domain */}
        <Card>
          <div className="flex items-center justify-between mb-4 gap-4 flex-wrap">
            <SectionLabel>Yearly Output by Domain</SectionLabel>
            <select
              value={selectedDomain}
              onChange={(event) => setSelectedDomain(event.target.value)}
              className="border border-[var(--color-line)] rounded-sm px-3 py-1.5 text-sm"
            >
              {domains.map((domain) => (
                <option key={domain} value={domain}>
                  {domain}
                </option>
              ))}
            </select>
          </div>

          <ResponsiveContainer width="100%" height={300}>
            <LineChart data={domainSeries}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="year" />
              <YAxis />
              <Tooltip />
              <Legend />
              <Line type="monotone" dataKey="publications" stroke={NAVY} />
              <Line type="monotone" dataKey="patents" stroke={OCHRE} />
              <Line type="monotone" dataKey="theses" stroke="#6f6c7f" />
            </LineChart>
          </ResponsiveContainer>
        </Card>

        {/* CAGR */}
        <Card>
          <SectionLabel>Top Domains by CAGR (%)</SectionLabel>
          <ResponsiveContainer width="100%" height={340}>
            <BarChart data={topCAGR} layout="vertical" margin={{ left: 160 }}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis type="number" />
              <YAxis type="category" dataKey="domain" width={160} tick={{ fontSize: 11 }} />
              <Tooltip />
              <Bar dataKey="cagr" fill={OCHRE} />
            </BarChart>
          </ResponsiveContainer>
        </Card>

        {/* Emerging domains */}
        <Card>
          <SectionLabel>Emerging Domains</SectionLabel>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-[var(--color-muted)] border-b border-[var(--color-line)]">
                  <th className="py-2">Domain</th>
                  <th className="py-2">Total</th>
                  <th className="py-2">Institutions</th>
                  <th className="py-2">Research Score</th>
                </tr>
              </thead>
              <tbody>
                {emergingDomains.slice(0, 10).map((row) => (
                  <tr key={row.domain} className="border-b border-[var(--color-line)]">
                    <td className="py-2">{row.domain}</td>
                    <td className="py-2">{row.total}</td>
                    <td className="py-2">{row.institutions}</td>
                    <td className="py-2">{row.researchScore}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>

        {/* Institution CAGR */}
        <Card>
          <SectionLabel>Institution Growth</SectionLabel>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-[var(--color-muted)] border-b border-[var(--color-line)]">
                  <th className="py-2">Institution</th>
                  <th className="py-2">CAGR %</th>
                  <th className="py-2">Trend</th>
                </tr>
              </thead>
              <tbody>
                {institutionCAGR.slice(0, 10).map((row) => (
                  <tr key={row.institution} className="border-b border-[var(--color-line)]">
                    <td className="py-2">{row.institution}</td>
                    <td className="py-2">{row.cagr}</td>
                    <td className="py-2">
                      <Badge tone="accent">{row.trend}</Badge>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>

        {/* Grant impact */}
        <Card>
          <SectionLabel>Grant Impact</SectionLabel>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-[var(--color-muted)] border-b border-[var(--color-line)]">
                  <th className="py-2">#</th>
                  <th className="py-2">Institution</th>
                  <th className="py-2">Projects</th>
                  <th className="py-2">Funding (Lakhs)</th>
                  <th className="py-2">Impact Score</th>
                </tr>
              </thead>
              <tbody>
                {grantImpact.slice(0, 10).map((row) => (
                  <tr key={row.institution} className="border-b border-[var(--color-line)]">
                    <td className="py-2">{row.rank}</td>
                    <td className="py-2">{row.institution}</td>
                    <td className="py-2">{row.totalProjects}</td>
                    <td className="py-2">{row.totalFundingLakhs}</td>
                    <td className="py-2">{row.impactScore}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>

        {/* Top researchers — NOTE: these arrive as raw CSV strings */}
        <Card>
          <SectionLabel>Top Researchers</SectionLabel>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-[var(--color-muted)] border-b border-[var(--color-line)]">
                  <th className="py-2">#</th>
                  <th className="py-2">Researcher</th>
                  <th className="py-2">Institution</th>
                  <th className="py-2">Publications</th>
                  <th className="py-2">Score</th>
                </tr>
              </thead>
              <tbody>
                {topResearchers.slice(0, 10).map((row, index) => (
                  <tr key={index} className="border-b border-[var(--color-line)]">
                    <td className="py-2">{row.rank}</td>
                    <td className="py-2">{row.researcher}</td>
                    <td className="py-2">{row.institution}</td>
                    <td className="py-2">{row.publications}</td>
                    <td className="py-2">{row.research_score}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      </div>
    </DashboardLayout>
  );
}