import pandas as pd
import json
import os
from pathlib import Path

# =====================================================
# SMART REPORT BUILDER
# =====================================================

# Your current project stores the analytics generated by the
# NLP/trend engine here.
OUTPUT_PATH = Path("nlp/trend_engine/outputs")

# Keep the report JSON/PDF in the existing report-engine folder.
REPORT_OUTPUT_PATH = Path("trend_engine/report_engine/generated_reports")


# =====================================================
# FILE / DATA HELPERS
# =====================================================

def load_csv(filename, required=True):
    """
    Load an analytics CSV and strip whitespace from column names.

    The report engine is normally run from the SMART project root.
    """
    path = OUTPUT_PATH / filename

    if not path.exists():
        if required:
            raise FileNotFoundError(
                f"Required analytics file not found:\n{path}\n"
                f"Run the trend-engine analytics scripts first."
            )
        return pd.DataFrame()

    df = pd.read_csv(path)
    df.columns = df.columns.astype(str).str.strip()
    return df


def find_optional_csv(candidates):
    """
    Find the first available CSV from a list of possible names.
    This makes the report builder work with the different analytics
    filenames used during SMART development.
    """
    for filename in candidates:
        path = OUTPUT_PATH / filename
        if path.exists():
            df = pd.read_csv(path)
            df.columns = df.columns.astype(str).str.strip()
            print(f"Using optional analytics file: {path}")
            return df

    return pd.DataFrame()


def normalize_text(value):
    if value is None:
        return ""
    return " ".join(str(value).strip().lower().split())


def to_number(value, default=0):
    if value is None:
        return default

    try:
        if pd.isna(value):
            return default
    except Exception:
        pass

    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def number_or_int(value):
    value = to_number(value, 0)
    return int(value) if float(value).is_integer() else round(value, 2)


def get_domain_col(df, label="df"):
    possible_columns = [
        "domain_name",
        "domain",
        "subdomain",
        "topic_label",
        "topic"
    ]

    for col in possible_columns:
        if col in df.columns:
            return col

    print(
        f"Warning: No domain column found in {label}. "
        f"Columns: {df.columns.tolist()}"
    )
    return None


def get_year_col(df):
    for col in ["year", "Year", "publication_year"]:
        if col in df.columns:
            return col
    return None


def get_institution_col(df):
    for col in [
        "institution",
        "Institution",
        "institution_name",
        "Institution Name"
    ]:
        if col in df.columns:
            return col
    return None


def filter_domain_year(df, technology, year, label="df"):
    """
    Filter using normalized strings so that differences such as:
    'Data Science and Knowledge Discovery'
    vs
    'Data Science and Knowledge Discovery '
    do not break report generation.
    """
    if df.empty:
        return df

    domain_col = get_domain_col(df, label)
    year_col = get_year_col(df)

    if domain_col is None:
        return pd.DataFrame()

    mask = df[domain_col].map(normalize_text) == normalize_text(technology)

    if year_col is not None:
        numeric_year = pd.to_numeric(df[year_col], errors="coerce")
        mask &= numeric_year == int(year)

    return df.loc[mask].copy()


def calculate_output(row):
    """
    Determine total research output from whichever fields the
    institution analytics file contains.
    """
    # Prefer an already calculated total.
    for key in [
        "total_output",
        "total_research",
        "research_output",
        "total"
    ]:
        if key in row and pd.notna(row[key]):
            return to_number(row[key], 0)

    # Otherwise calculate from the four SMART output types.
    component_keys = ["publications", "patents", "grants", "theses"]

    values = []
    found_component = False

    for key in component_keys:
        if key in row:
            found_component = True
            values.append(to_number(row[key], 0))

    if found_component:
        return sum(values)

    return None


# =====================================================
# INSTITUTION ANALYTICS
# =====================================================

def build_top_institutions(technology, year, researchers):
    """
    Build institution rankings for the SELECTED domain + year.

    IMPORTANT:
    The old implementation incorrectly used grant_impact_score.csv
    for top institutions. That file contains institution-level grant
    metrics and does not contain the selected domain, so it produced
    unrelated institutions and then the PDF displayed 0 research
    output for them.

    This function first looks for a real institution/domain/year
    analytics file. If none exists, it uses researcher publications
    as a clearly labelled fallback instead of pretending those values
    are total research output.
    """

    # These cover the institution analytics filenames used by the
    # SMART trend/institute analytics pipeline.
    institution_df = find_optional_csv([
        "institution_domain_yearly_counts.csv",
        "institution_domain_yearly_output.csv",
        "institution_analytics.csv",
        "institution_domain_counts.csv",
        "institution_yearly_counts.csv",
        "institution_totals.csv"
    ])

    if not institution_df.empty:
        institution_col = get_institution_col(institution_df)
        domain_col = get_domain_col(institution_df, "institution analytics")
        year_col = get_year_col(institution_df)

        if institution_col and domain_col and year_col:
            filtered = filter_domain_year(
                institution_df,
                technology,
                year,
                "institution analytics"
            )

            if not filtered.empty:
                rows = []

                # If multiple rows exist for an institution, aggregate them.
                for institution, group in filtered.groupby(institution_col):
                    total = 0
                    has_value = False

                    for _, row in group.iterrows():
                        value = calculate_output(row)

                        if value is not None:
                            total += value
                            has_value = True

                    if has_value:
                        rows.append({
                            "institution": str(institution),
                            "total_output": number_or_int(total)
                        })

                rows.sort(
                    key=lambda x: to_number(x["total_output"], 0),
                    reverse=True
                )

                for rank, row in enumerate(rows[:10], start=1):
                    row["rank"] = rank

                print(
                    f"Top institutions loaded from institution analytics: "
                    f"{len(rows[:10])}"
                )

                return rows[:10]

    # ---------------------------------------------------------
    # Fallback: researcher publication contribution
    # ---------------------------------------------------------
    #
    # This is NOT labelled as total research output because the
    # researcher file normally contains publication counts only.
    # It is better to provide an honest publication-based ranking
    # than to show false zeros.
    # ---------------------------------------------------------

    if not researchers.empty:
        domain_col = get_domain_col(researchers, "researchers")
        institution_col = get_institution_col(researchers)

        if domain_col and institution_col and "publications" in researchers.columns:
            filtered = filter_domain_year(
                researchers,
                technology,
                year,
                "researchers"
            )

            # If researcher analytics has no year column, filter the
            # domain only. This preserves compatibility with the
            # existing domain_top_researchers.csv.
            if filtered.empty and get_year_col(researchers) is None:
                filtered = researchers[
                    researchers[domain_col].map(normalize_text)
                    == normalize_text(technology)
                ].copy()

            if not filtered.empty:
                grouped = (
                    filtered.assign(
                        publications_numeric=pd.to_numeric(
                            filtered["publications"],
                            errors="coerce"
                        ).fillna(0)
                    )
                    .groupby(institution_col)["publications_numeric"]
                    .sum()
                    .sort_values(ascending=False)
                )

                rows = []

                for rank, (institution, publications) in enumerate(
                    grouped.head(10).items(),
                    start=1
                ):
                    rows.append({
                        "rank": rank,
                        "institution": str(institution),
                        "total_output": number_or_int(publications),
                        "research_output": number_or_int(publications),
                        "output_type": "publications"
                    })

                if rows:
                    print(
                        "Warning: No institution/domain/year output file "
                        "was found. Using institution publication totals "
                        "as a fallback."
                    )
                    return rows

    print(
        "Warning: No institution analytics available for "
        f"domain='{technology}' year={year}."
    )

    return []


# =====================================================
# REPORT BUILDER
# =====================================================

def build_report(technology, year):

    print("=" * 70)
    print("SMART TECHNOLOGY REPORT")
    print("=" * 70)
    print(f"Technology : {technology}")
    print(f"Year       : {year}")
    print()

    # =====================================================
    # LOAD ANALYTICS
    # =====================================================

    domain_counts = load_csv("domain_yearly_counts.csv")
    domain_growth = load_csv("domain_yoy_growth.csv")
    domain_cagr = load_csv("domain_cagr.csv")
    researchers = load_csv("domain_top_researchers.csv")
    grants = load_csv("grant_impact_score.csv")
    journals = load_csv("top_journals.csv")
    conferences = load_csv("top_conferences.csv")

    venues_path = OUTPUT_PATH / "domain_top_venues.csv"

    if venues_path.exists():
        venues = pd.read_csv(venues_path)
        venues.columns = venues.columns.astype(str).str.strip()
    else:
        venues = pd.DataFrame()

    print("domain_counts columns :", domain_counts.columns.tolist())
    print("domain_growth columns :", domain_growth.columns.tolist())
    print("domain_cagr columns   :", domain_cagr.columns.tolist())
    print("researchers columns   :", researchers.columns.tolist())
    print("grants columns        :", grants.columns.tolist())
    print()

    # =====================================================
    # DETECT COLUMNS
    # =====================================================

    counts_domain_col = get_domain_col(domain_counts, "domain_counts")
    growth_domain_col = get_domain_col(domain_growth, "domain_growth")
    cagr_domain_col = get_domain_col(domain_cagr, "domain_cagr")
    researcher_domain_col = get_domain_col(researchers, "researchers")

    # =====================================================
    # REPORT OBJECT
    # =====================================================

    report = {
        "technology": technology,
        "year": int(year),
        "publication_statistics": {},
        "growth_statistics": {},
        "grant_statistics": {},
        "top_researchers": [],
        "top_institutions": [],
        "top_journals": [],
        "top_conferences": [],
        "top_venues": [],
        "executive_summary": "",
        "recommendations": []
    }

    # =====================================================
    # PUBLICATION STATISTICS
    # =====================================================

    year_row = pd.DataFrame()

    if counts_domain_col:
        year_col = get_year_col(domain_counts)

        mask = (
            domain_counts[counts_domain_col].map(normalize_text)
            == normalize_text(technology)
        )

        if year_col:
            mask &= (
                pd.to_numeric(
                    domain_counts[year_col],
                    errors="coerce"
                ) == int(year)
            )

        year_row = domain_counts.loc[mask]

    if year_row.empty:
        print(
            f"Warning: No data for domain='{technology}' year={year}"
        )
        publications = patents = grants_count = theses = total_output = 0

    else:
        row = year_row.iloc[0]

        publications = number_or_int(
            row.get("publications", 0)
        )

        patents = number_or_int(
            row.get("patents", 0)
        )

        grants_count = number_or_int(
            row.get("grants", 0)
        )

        theses = number_or_int(
            row.get("theses", 0)
        )

        calculated_total = (
            publications
            + patents
            + grants_count
            + theses
        )

        total_value = row.get(
            "total_research",
            row.get("total", calculated_total)
        )

        total_output = number_or_int(
            total_value
        )

    report["publication_statistics"] = {
        "publications": publications,
        "patents": patents,
        "grants": grants_count,
        "theses": theses,
        "total_output": total_output
    }

    # =====================================================
    # GROWTH STATISTICS
    # =====================================================

    yoy_growth = 0.0

    if growth_domain_col:
        growth_year_col = get_year_col(domain_growth)

        mask = (
            domain_growth[growth_domain_col].map(normalize_text)
            == normalize_text(technology)
        )

        if growth_year_col:
            mask &= (
                pd.to_numeric(
                    domain_growth[growth_year_col],
                    errors="coerce"
                ) == int(year)
            )

        growth_row = domain_growth.loc[mask]

        if not growth_row.empty:
            yoy_val = growth_row.iloc[0].get(
                "yoy_growth_percent",
                growth_row.iloc[0].get("total_yoy", 0)
            )

            yoy_growth = round(
                to_number(yoy_val, 0),
                2
            )

    # =====================================================
    # CAGR
    # =====================================================

    cagr_val = 0.0

    if cagr_domain_col:
        cagr_row = domain_cagr[
            domain_cagr[cagr_domain_col].map(normalize_text)
            == normalize_text(technology)
        ]

        if not cagr_row.empty:
            cagr_val = round(
                to_number(
                    cagr_row.iloc[0].get("cagr_percent", 0),
                    0
                ),
                2
            )

    report["growth_statistics"] = {
        "yoy_growth_percent": yoy_growth,
        "cagr_percent": cagr_val
    }

    # =====================================================
    # GRANT STATISTICS
    # =====================================================

    grant_domain_col = get_domain_col(
        grants,
        "grants"
    )

    avg_impact = 0.0
    grant_scope = "overall"

    if grant_domain_col:

        domain_grants = grants[
            grants[grant_domain_col].map(normalize_text)
            == normalize_text(technology)
        ]

        grant_scope = "selected technology"

    else:
        # grant_impact_score.csv in the current SMART pipeline
        # has no domain column. Therefore do NOT pretend its
        # average is technology-specific.
        domain_grants = grants

        print(
            "Grant data has no domain column. "
            "Average Grant Impact Score is overall."
        )

    if (
        not domain_grants.empty
        and "impact_score" in domain_grants.columns
    ):
        scores = pd.to_numeric(
            domain_grants["impact_score"],
            errors="coerce"
        ).dropna()

        if not scores.empty:
            avg_impact = round(
                float(scores.mean()),
                2
            )

    report["grant_statistics"] = {
        "average_impact_score": avg_impact,
        "scope": grant_scope
    }

    # =====================================================
    # TOP RESEARCHERS
    # =====================================================

    if researcher_domain_col:

        filtered_researchers = researchers[
            researchers[researcher_domain_col].map(normalize_text)
            == normalize_text(technology)
        ].copy()

    else:

        filtered_researchers = researchers.copy()

    if "research_score" in filtered_researchers.columns:

        filtered_researchers["research_score_numeric"] = pd.to_numeric(
            filtered_researchers["research_score"],
            errors="coerce"
        ).fillna(0)

        top_res = (
            filtered_researchers
            .sort_values(
                "research_score_numeric",
                ascending=False
            )
            .head(10)
        )

    else:

        top_res = filtered_researchers.head(10)

    cols_res = [
        c for c in [
            "rank",
            "researcher",
            "institution",
            "publications",
            "citations",
            "research_score"
        ]
        if c in top_res.columns
    ]

    report["top_researchers"] = (
        top_res[cols_res]
        .fillna("")
        .to_dict("records")
    )

    # =====================================================
    # TOP INSTITUTIONS — FIXED
    # =====================================================

    report["top_institutions"] = build_top_institutions(
        technology,
        year,
        researchers
    )

    # =====================================================
    # TOP JOURNALS + CONFERENCES
    # =====================================================

    report["top_journals"] = (
        journals
        .head(10)
        .fillna("")
        .to_dict("records")
    )

    report["top_conferences"] = (
        conferences
        .head(10)
        .fillna("")
        .to_dict("records")
    )

    # =====================================================
    # TOP VENUES FOR THIS DOMAIN
    # =====================================================

    if not venues.empty:

        venue_domain_col = get_domain_col(
            venues,
            "venues"
        )

        if venue_domain_col:

            report["top_venues"] = (
                venues[
                    venues[venue_domain_col].map(normalize_text)
                    == normalize_text(technology)
                ]
                .head(10)
                .fillna("")
                .to_dict("records")
            )

        else:

            report["top_venues"] = (
                venues
                .head(10)
                .fillna("")
                .to_dict("records")
            )

    # =====================================================
    # EXECUTIVE SUMMARY
    # =====================================================

    pub = report["publication_statistics"]
    growth = report["growth_statistics"]
    grant = report["grant_statistics"]

    grant_scope_text = (
        "for the selected technology"
        if grant["scope"] == "selected technology"
        else "across the available grant dataset"
    )

    report["executive_summary"] = (
        f"The {technology} domain produced "
        f"{pub['total_output']} total research outputs in {year}, "
        f"including {pub['publications']} publications, "
        f"{pub['patents']} patents, "
        f"{pub['grants']} grants and "
        f"{pub['theses']} theses. "
        f"The year-on-year growth was "
        f"{growth['yoy_growth_percent']}%, "
        f"while the long-term CAGR stands at "
        f"{growth['cagr_percent']}%. "
        f"The average Grant Impact Score "
        f"{grant_scope_text} was "
        f"{grant['average_impact_score']}."
    )

    # =====================================================
    # RECOMMENDATIONS
    # =====================================================

    recs = []

    if growth["yoy_growth_percent"] > 20:

        recs.append(
            "Strong growth detected. Continued investment is recommended."
        )

    elif growth["yoy_growth_percent"] > 0:

        recs.append(
            "Steady growth observed. Monitor emerging research trends."
        )

    else:

        recs.append(
            "Research output has declined. "
            "Strategic funding and collaboration should be encouraged."
        )

    if growth["cagr_percent"] > 15:

        recs.append(
            "Long-term CAGR indicates this technology is emerging rapidly."
        )

    if pub["publications"] > 500:

        recs.append(
            "High publication volume supports international collaboration."
        )

    if grant["average_impact_score"] > 50:

        recs.append(
            "Grant funding performance is strong across the available data."
        )

    else:

        recs.append(
            "Grant funding should be strengthened to improve "
            "technology development."
        )

    report["recommendations"] = recs

    # =====================================================
    # PRINT REPORT
    # =====================================================

    print("=" * 70)
    print("REPORT GENERATED")
    print("=" * 70)

    print(
        f"\nTechnology : {report['technology']}"
    )

    print(
        f"Year       : {report['year']}"
    )

    print(
        "\nPublication Statistics"
    )

    print(
        report["publication_statistics"]
    )

    print(
        "\nGrowth Statistics"
    )

    print(
        report["growth_statistics"]
    )

    print(
        "\nGrant Statistics"
    )

    print(
        report["grant_statistics"]
    )

    print(
        f"\nTop Researchers  : "
        f"{len(report['top_researchers'])}"
    )

    print(
        f"Top Institutions : "
        f"{len(report['top_institutions'])}"
    )

    print(
        f"Top Journals     : "
        f"{len(report['top_journals'])}"
    )

    print(
        f"Top Conferences  : "
        f"{len(report['top_conferences'])}"
    )

    print(
        "\nTop Institutions"
    )

    for institution in report["top_institutions"]:

        print(
            f"  {institution.get('rank', '')}. "
            f"{institution.get('institution', '')} -> "
            f"{institution.get('total_output', 'N/A')}"
        )

    print(
        "\nExecutive Summary"
    )

    print(
        report["executive_summary"]
    )

    print(
        "\nRecommendations"
    )

    for recommendation in report["recommendations"]:

        print(
            "-",
            recommendation
        )

    # =====================================================
    # SAVE REPORT AS JSON
    # =====================================================

    REPORT_OUTPUT_PATH.mkdir(
        parents=True,
        exist_ok=True
    )

    safe_technology = (
        normalize_text(technology)
        .replace("&", "and")
        .replace("/", "_")
        .replace(" ", "_")
    )

    file_name = (
        safe_technology
        + "_"
        + str(year)
        + ".json"
    )

    save_path = (
        REPORT_OUTPUT_PATH
        / file_name
    )

    with open(
        save_path,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            report,
            f,
            indent=4,
            ensure_ascii=False
        )

    print()
    print("=" * 70)
    print("REPORT SAVED")
    print("=" * 70)
    print(save_path)

    return report


# =====================================================
# RUN
# =====================================================

if __name__ == "__main__":

    from pdf_generator import generate_pdf

    report = build_report(
        "Artificial Intelligence and Computer Vision",
        2023
    )

    pdf_path = generate_pdf(
        report
    )

    print(
        f"\nPDF saved to: {pdf_path}"
    )